### ISSUE TITLE
Fix js coding style

### ISSUE THREAD

**Issue by RainyRuRu** [TSY-and-CIJ/GitHub-Pages-base#5]
https://github.com/TSY-and-CIJ/GitHub-Pages-base/blob/master/src/components/Rating.vue#L23

這種地方可以直接寫成 
```
functionName() {
 ... your code
}
```

**Comment by snoopy2199** [comment]
@RainyRuRu verify please ❤️

**Comment by RainyRuRu** [comment]
Nice !
